[pytest]
# Эти флаги будут добавляться автоматически к любой команде pytest
addopts = --alluredir=allure-results --html=reports/report.html --self-contained-html

# Указываем, где искать тесты
testpaths = tests/ui

# Шаблоны имен файлов и функций для тестов
python_files = test_*.py
python_functions = test_* 